name: run test image no background 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
 workflow_dispatch:
    inputs:
      name:
        description: "test"
        default: "test"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel


jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dowta
          password: dowta2012
      -
        name: run docker image

        run: docker run dowta/test_image:latest 

