name: run docker image in background 01

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
 workflow_dispatch:
    inputs:
      name:
        description: "test"
        default: "test"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel


jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dowta
          password: dowta2012
      -
        name: run docker image
        run: docker run -d dowta/mynewbackend:latest 
      -
        name: Send HTTP request
        id: request
        uses: tyrrrz/action-http-request@master
        with:
          url: http://localhost:80/predict
          method: POST
          headers: |
            Content-Type: application/json
          body: |
            {
              "text": "This is wonderfull"
            }
          retry-count: 3
          retry-delay: 500

      - 
          name: Print outputs
          run: |
            echo "Status: ${{ steps.request.outputs.status }}"
            echo "Success: ${{ steps.request.outputs.success }}"